name: "PR Pipeline B"

on:
  workflow_run:
    workflows:
      - 'PR Pipeline A'
    branches:
      - 'stage/*'
    types:
      - 'completed'

jobs:
  first:
    uses: chrismj/such-action/.github/workflows/actionb.yml@main
