name: "Staging PR Pipeline B"
on:
  workflow_run:
    workflows:
      - 'Staging PR Pipeline A'
    branches:
      - staging
    types:
      - completed

jobs:
  merge-pr:
    name: Auto merge PR
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Merge Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          LOCAL_BASE: ${{ github.event.workflow_run.head_branch }}
        run: gh pr merge "${LOCAL_BASE}" --auto --merge

      - name: testing 
        run: ls -last

      - name: Checkout main
        run: git checkout main

      - name: Sync main post PR merge
        run: git pull

      - name: Checkout branch
        env:
          LOCAL_BASE: ${{ github.event.workflow_run.head_branch }}
        run: git checkout "${LOCAL_BASE}"

      - name: Sync branch
        run: git pull

      - name: Merge main into branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          LOCAL_BASE: ${{ github.event.workflow_run.head_branch }}
        run: git merge main

      - name: Push branch
        run: git push

