name: "Staging PR Pipeline B"

on:
  workflow_run:
    workflows:
      - 'Staging PR Pipeline A'
    branches:
      - 'stage/*'
    types:
      - 'completed'

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/actionb.yml
