name: "Stage PR Pipeline A"

on:
  push:
    branches:
      - 'stage/*'
    paths:
      - 'i18n/*'

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/actiona.yml

