name: "Staging PR Pipeline 5"
on: pull_request

jobs:
  merge-pr:
    name: Auto merge PR
    runs-on: ubuntu-latest
    steps:
      - name: echo test
        run: echo ${{ github.head_ref }}

      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}

      - name: Merge Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          LOCAL_BASE: ${{ github.head_ref }}
        run: gh pr merge "${LOCAL_BASE}" --auto --merge
