name: "Staging PR Pipeline B"

on:
  workflow_run:
    workflows:
      - 'Staging PR Pipeline A'
    branches:
      - staging
    types:
      - completed

env:
  RELEASE_BRANCH: main
  LOCAL_BASE: ${{ github.event.workflow_run.head_branch }}

jobs:
  merge-pr:
    name: Auto merge PR
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout local base branch
        uses: actions/checkout@v6
        with:
          ref: $LOCAL_BASE
          fetch-depth: 0

      - name: Merge Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: gh pr merge "${LOCAL_BASE}" --auto --merge

      - name: Checkout release branch
        run: git checkout "${RELEASE_BRANCH}"

      - name: Sync release branch post PR merge
        run: git pull

      - name: Checkout local base branch
        run: git checkout "${LOCAL_BASE}"

      - name: Sync local base branch
        run: git pull

      - name: Merge release branch into local base branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: git merge "${RELEASE_BRANCH}"

      - name: Push local base branch
        run: git push

