name: ReleasePush
run-name: "ReleasePush ${{ github.event.number }} (${{ github.event.action }}) by ${{ github.actor }}"

on:
  push:
    branches:
      - 'release/*'

jobs:
  wrapper:
    uses: chrsmj/such-action/.github/workflows/SharedReleasePush.yml@main
