name: ReleasePush
run-name: "ReleasePush ${{ github.run_id }}/${{ github.run_number }}/${{ github.run_attempt }} (${{ github.action }}) by @${{ github.actor }}"

on:
  push:
    branches:
      - 'release/*'

jobs:
  wrap:
    uses: chrsmj/such-action/.github/workflows/SharedReleasePush.yml@main
