name: SharedStageMerge
run-name: "SharedStageMerge ${{ github.event.number }} (${{ github.event.action }}) by ${{ github.actor }}"
on:
  workflow_call:

permissions:
  actions: read
  checks: read
  contents: write
  issues: read
  pull-requests: write
  repository-projects: read
  statuses: read

env:
  LOCAL_BASE: ${{ github.event.workflow_run.head_branch }}
  RELEASE_BRANCH: ${{ endsWith(github.event.workflow_run.head_branch,'1') && 'release/1' ||
                      endsWith(github.event.workflow_run.head_branch,'2') && 'release/2' ||
                      endsWith(github.event.workflow_run.head_branch,'3') && 'release/3' ||
                      'release/0' }}

jobs:
  MergePR:
    name: Auto merge PR
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout action
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Merge Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: gh pr merge "${LOCAL_BASE}" --auto --merge

      - name: Checkout release branch
        run: git checkout "${RELEASE_BRANCH}"

      - name: Sync release branch post PR merge
        run: git pull

      - name: Checkout local base branch
        run: git checkout "${LOCAL_BASE}"

      - name: Sync local base branch
        run: git pull

      - name: Merge release branch into local base branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: git merge "${RELEASE_BRANCH}"

      - name: Push local base branch
        run: git push

