name: StageMerge
run-name: "StageMerge ${{ github.run_number }}/${{ github.run_attempt }} (${{ github.event_name }}) by @${{ github.actor }}"

on:
  workflow_run:
    workflows:
      - 'StagePush'
    branches:
      - 'stage/*'
    types:
      - 'completed'

jobs:
  wrap:
    uses: chrsmj/such-action/.github/workflows/SharedStageMerge.yml@main
