name: StagePush
run-name: "StagePush ${{ github.run_number }}/${{ github.run_attempt }} (${{ github.event_name }}) by @${{ github.actor }}"

on:
  push:
    branches:
      - 'stage/*'
    paths:
      - 'i18n/*'

jobs:
  wrap:
    uses: chrsmj/such-action/.github/workflows/SharedStagePush.yml@main
