name: StageMerge
run-name: "StageMerge ${{ github.event.number }} (${{ github.event.action }}) by ${{ github.actor }}"

on:
  workflow_run:
    workflows:
      - 'StagePush'
    branches:
      - 'stage/*'
    types:
      - 'completed'

jobs:
  wrapper:
    uses: chrsmj/such-action/.github/workflows/SharedStageMerge.yml@main
