name: StageMerge

on:
  workflow_run:
    workflows:
      - 'StagePush'
    branches:
      - 'stage/*'
    types:
      - 'completed'

jobs:
  first:
    uses: chrsmj/such-action/.github/workflows/SharedStageMerge.yml@main
