name: StagePush
run-name: "StagePush ${{ github.event.number }} (${{ github.event.action }}) by ${{ github.actor }}"

on:
  push:
    branches:
      - 'stage/*'
    paths:
      - 'i18n/*'

jobs:
  wrapper:
    uses: chrsmj/such-action/.github/workflows/SharedStagePush.yml@main
